#!/bin/bash

set -ex

uv run python -m isort .
uv run python -m black .
uv run python -m isort --check-only .
uv run python -m black --check .
uv run python -m flake8 src tests
uv run python -m mypy src tests
